AWSTemplateFormatVersion: "2010-09-09"
Description: "template description"

Resources:
  CodeBucket:
    Type: AWS::S3::Bucket
  FrontAppS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref FrontAppS3Bucket
                - /*
      Bucket: !Ref FrontAppS3Bucket

Outputs:
  BucketName:
    Value: !Ref CodeBucket
    Description: Name of the sample Amazon S3 bucket with the source code for lambda functions.
    Export:
      Name: !Sub "${AWS::StackName}-CodeBucketName"
  WebsiteURL:
    Value: !GetAtt 
      - FrontAppS3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  FrontAppS3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - FrontAppS3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content
