AWSTemplateFormatVersion: '2010-09-09'
# *** Change this to something useful for you!
Description: template for creating pipelines

Parameters:
  RepoOwner:
    Type: String
    Default: alexnawr
  RepoName:
    Type: String
    Default: 'cc' 
  RepoBranch:
    Type: String
    Default: 'main'
  BucketsStackName:
    Type: String
    Default: 'BucketsStack'
  LambdasStackName:
    Type: String
    Default: 'LambdasStack'
  ApiGatewayStackName:
    Type: String
    Default: 'ApiGatewayStack'
  PipelineRole:
    Type: String
    Default: arn:aws:iam::980494704750:role/LabRole

Resources:
  PipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactsBucket
      RestartExecutionOnUpdate: true
      RoleArn: !Ref PipelineRole
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          InputArtifacts: []
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: 1
            Provider: GitHub
          OutputArtifacts:
          - Name: SourceCode
          Configuration:
            Owner: !Ref RepoOwner
            Repo: !Ref RepoName
            Branch: !Ref RepoBranch
            PollForSourceChanges: false
            OAuthToken: "{{resolve:ssm-secure:GithubToken:0}}"
          RunOrder: 1
      - Name: Deploy
        Actions:
        - Name: BucketDeploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          InputArtifacts:
            - Name: SourceCode
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_IAM
            RoleArn: !Ref PipelineRole
            StackName: !Ref BucketsStackName
            TemplatePath: !Sub "SourceCode::templates/buckets.yaml"
        - Name: LambdaDeploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          InputArtifacts:
            - Name: SourceCode
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_IAM
            RoleArn: !Ref PipelineRole
            StackName: !Ref LambdasStackName
            TemplatePath: !Sub "SourceCode::templates/lambdas.yaml"
        - Name: ApiGatewayDeploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          InputArtifacts:
            - Name: SourceCode
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_IAM
            RoleArn: !Ref PipelineRole
            StackName: !Ref ApiGatewayStackName
            TemplatePath: !Sub "SourceCode::templates/api_gateway.yaml"
          RunOrder: 1     


  GithubWebhook:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: "{{resolve:ssm-secure:GithubToken:0}}"
      RegisterWithThirdParty: 'true'
      Filters:
      - JsonPath: "$.ref"
        MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Ref CodePipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt CodePipeline.Version


